server {
    listen 4200;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Long-cache hashed assets; short-cache index
    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    location /assets/ {
        access_log off;
        expires 7d;
        add_header Cache-Control "public";
    }
}
