server.port=8082
server.address=0.0.0.0

file.root-path=${FILE_ROOT_PATH:../data}
file.max-upload-size=5368709120

spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB

app.jwt.secret=${JWT_SECRET:FileBridgeDevSecretKeyChangeMeInProduction_32charsMin}
app.jwt.expiration-ms=86400000
app.auth.username=${FILEBRIDGE_USER:admin}
app.auth.password=${FILEBRIDGE_PASSWORD:admin123}

spring.web.resources.static-locations=classpath:/static/
